import { v2 as cloudinary } from 'cloudinary';
import fs from 'fs';
import FoodModel from '../models/Foodmodel.js';

// Configure Cloudinary using your Environment Variables
cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET
});

/**
 * Helper function to extract Cloudinary Public ID from a full secure URL
 * Example: "https://res.cloudinary.com/cloud_name/image/upload/v12345/foodora_products/17123_food.png"
 * Returns: "foodora_products/17123_food"
 */
const getCloudinaryPublicId = (url) => {
    try {
        const parts = url.split('/upload/');
        if (parts.length < 2) return null;
        
        // Remove version tag (e.g., "v17123/") if it exists
        const withoutVersion = parts[1].replace(/^v\d+\//, '');
        
        // Strip the file extension (e.g., ".png")
        const publicId = withoutVersion.substring(0, withoutVersion.lastIndexOf('.'));
        return publicId;
    } catch (error) {
        console.error("Failed to parse public ID from URL:", error);
        return null;
    }
};

// Add food item
export const addFood = async (req, res) => {
    // Check if multer successfully captured the file
    if (!req.file) {
        return res.status(400).json({ success: false, message: "No image file provided" });
    }

    try {
        // 1. Upload local temporary file generated by multer to Cloudinary
        const result = await cloudinary.uploader.upload(req.file.path, {
            folder: "foodora_products" // Saves inside a dedicated directory in your Cloudinary account
        });

        // 2. Clear local storage: Safely delete the temporary file from your local uploads folder
        if (fs.existsSync(req.file.path)) {
            fs.unlinkSync(req.file.path);
        }

        // 3. Extract the body parameters
        const { name, price, description, category } = req.body;

        // 4. Create the new database record, saving Cloudinary's permanent HTTPS URL
        const food = new FoodModel({ 
            name, 
            price, 
            description, 
            category, 
            image: result.secure_url // Saves "https://res.cloudinary.com/..."
        });

        await food.save();
        res.status(201).json({ success: true, message: "Food item added successfully" });
    } catch (error) {
        // Safe Cleanup Fallback: Wipe the local file if the save or upload failed
        if (req.file && fs.existsSync(req.file.path)) {
            fs.unlinkSync(req.file.path);
        }
        console.error("Error adding food item:", error);
        res.status(500).json({ success: false, message: "Error adding food item" });
    }
};

// List foodData
export const listFood = async (req, res) => {
    try {
        const foodData = await FoodModel.find({});
        res.status(200).json({ success: true, Data: foodData });
    } catch (error) {
        console.error("Error listing food items:", error);
        res.status(500).json({ success: false, message: "Error getting food items" });
    }
};

// Delete foodData
export const deleteFood = async (req, res) => {
    const { id } = req.params;
    try {
        const food = await FoodModel.findById(id);

        if (!food) {
            return res.status(404).json({ success: false, message: "Food item not found" });
        }

        // Check if the image path is a Cloudinary URL or a legacy local string
        if (food.image && food.image.startsWith("http")) {
            // Path A: It's a Cloudinary URL, let's delete it from Cloudinary
            const publicId = getCloudinaryPublicId(food.image);
            if (publicId) {
                await cloudinary.uploader.destroy(publicId);
            }
        } else if (food.image) {
            // Path B: It's a legacy local image, delete it locally
            const localPath = `uploads/${food.image}`;
            if (fs.existsSync(localPath)) {
                fs.unlink(localPath, (err) => {
                    if (err) {
                        console.error("Error deleting local image:", err);
                    }
                });
            }
        }

        // Delete the database entry
        await FoodModel.findByIdAndDelete(id);

        res.status(200).json({ success: true, message: "Food item deleted successfully" });
    } catch (error) {
        console.error("Error deleting food item:", error);
        res.status(500).json({ success: false, message: "Error deleting food item" });
    }
};